// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SevenBridgeAMCProj.Models;

#nullable disable

namespace SevenBridgeAMCProj.Migrations
{
    [DbContext(typeof(SevenBridgeAMCContext))]
    [Migration("20240908133654_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SevenBridgeAMCProj.Models.SevenBridgeAMC", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Showtime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("SevenBridges");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Format = "Standard",
                            Name = "Casablanca",
                            Price = 10,
                            Showtime = "16:25"
                        },
                        new
                        {
                            MovieId = 2,
                            Format = "IMAX",
                            Name = "Wonder Woman",
                            Price = 9,
                            Showtime = "15:00"
                        },
                        new
                        {
                            MovieId = 3,
                            Format = "Standard",
                            Name = "Moonstruck",
                            Price = 7,
                            Showtime = "13:00"
                        },
                        new
                        {
                            MovieId = 4,
                            Format = "IMAX",
                            Name = "Oppenheimer",
                            Price = 10,
                            Showtime = "13:10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
